version: "3"
networks:
  kong-net:
    external: true
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: imclogin_client
    image: yknam/imclogin_client
    networks:
      - kong-net
    volumes:
      - ./src:/app/src
    ports:
      - "8005:80"
