version: "2"
networks:
  kong-net:
    external: true

services:
  imclogin:
    container_name: imcloginc
    image: yknam/imclogin
    environment:
      - MONGO_URI=mongodb://imcmongoc:27017/local
    restart: always
    build: .
    networks:
      - kong-net
    volumes:
      # //- jsondata:/data/json
      # - images:/data/images
      - /.env:/app/.env
    ports:
      - "9001:9001"
    external_links:
      - imcmongoc
