version: "2"
networks:
  kong-net:
    external: true
volumes:
  mongodbdatatest:
    external: true
services:
  imclogin:
    container_name: imclogin
    image: yknam/imclogin
    environment:
      - MONGO_URI=mongodb://imcmongoctest:27017/logintest
    restart: always
    build: .
    networks:
      - kong-net
    volumes:
      - /.env:/app/.env
    ports:
      - "6006:6006"
      # if you want to link to exsiting mongodb
      # use external_links(container name) as below
    # external_links:
    #   - imcmongoc

  imcmongotest:
    container_name: imcmongoctest
    image: mongo
    restart: always
    networks:
      - kong-net
    volumes:
      #- ../Program\ Files/MongoDB/Server/4.0/data:/data/db
      - mongodbdatatest:/data/db
    ports:
      - "6007:27017"
