version: "2"
networks:
  kong-net:
    external: true
volumes:
  mongodbdata:
    external: true
services:
  imclogin:
    container_name: imclogin
    image: yknam/imclogin
    environment:
      - MONGO_URI=mongodb://imcmongoc:27017/local
    restart: always
    build: .
    networks:
      - kong-net
    volumes:
      - /.env:/app/.env
    ports:
      - "9001:9001"
      # if you want to link to exsiting mongodb
      # use external_links(container name) as below
      external_links:
      - imcmongoc


  # imcmongo:
  #   container_name: imcmongoc
  #   image: yknam/imcmongo:first
  #   restart: always
  #   networks:
  #     - kong-net
  #   volumes:
  #     #- ../Program\ Files/MongoDB/Server/4.0/data:/data/db
  #     - mongodbdata:/data/db
  #   ports:
  #     - "9007:27017"
